# Generated by Django 3.2.3 on 2021-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusNo', models.CharField(max_length=10, verbose_name='BusNo')),
                ('Routes', models.CharField(max_length=500, verbose_name='Routes')),
                ('TD', models.CharField(max_length=500, verbose_name='TD')),
                ('TT', models.CharField(max_length=500, verbose_name='TT')),
            ],
        ),
    ]
