# Generated by Django 3.2.3 on 2021-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_no_of_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Routes',
            field=models.CharField(max_length=10000, verbose_name='Routes'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='TD',
            field=models.CharField(max_length=10000, verbose_name='TD'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='TT',
            field=models.CharField(max_length=10000, verbose_name='TT'),
        ),
    ]
