# Generated by Django 3.2.3 on 2021-07-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_buses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='BUS_NO',
            new_name='Bus_No',
        ),
    ]
