# Generated by Django 3.2.3 on 2021-07-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
