# Generated by Django 3.2.3 on 2021-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210709_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='Bus_Name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
