# Generated by Django 3.2.3 on 2021-07-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='availability',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Booking_Details',
        ),
        migrations.DeleteModel(
            name='Buses',
        ),
        migrations.DeleteModel(
            name='Selected_Buses',
        ),
    ]
