# Generated by Django 3.2.3 on 2021-06-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='traveler',
            new_name='no_of_travelers',
        ),
    ]
