# Generated by Django 3.2.3 on 2021-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability_from_and_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.CharField(max_length=100)),
                ('TO', models.CharField(max_length=100)),
            ],
        ),
    ]
