# Generated by Django 3.2.3 on 2021-06-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_availability_from_and_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS_NO', models.CharField(max_length=10)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Via', models.CharField(max_length=100)),
                ('Distance', models.IntegerField()),
                ('Type_Bus', models.CharField(max_length=100)),
                ('Type_Seat', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Timing', models.TimeField()),
                ('Day', models.CharField(max_length=15)),
            ],
        ),
    ]
