# Generated by Django 3.2.3 on 2021-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_bus_no_buses_bus_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.CharField(max_length=10)),
                ('Day', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('No_of_seats', models.IntegerField()),
            ],
        ),
    ]
