# Generated by Django 3.2.3 on 2021-07-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
