# Generated by Django 3.2.3 on 2021-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='Bus_No',
        ),
        migrations.AddField(
            model_name='buses',
            name='Bus_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
