# Generated by Django 3.2.3 on 2021-07-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_buses_bus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buses',
            old_name='Bus_Name',
            new_name='Bus_No',
        ),
    ]
